 version: "3"
 services:

  app:
   hostname: "app"
   image: php:fpm
   volumes:
           - ./code:/code     
   expose:
     - 9000
   links:
     - db
   networks:
    vp-network:
     aliases:
      - server1.docker      
  nginx:
   hostname: "nginx"
   image: nginx:latest
   ports:
     - "80:80"
   volumes:
     - ./code:/code
     - ./site.conf:/etc/nginx/conf.d/default.conf
   links:
     - app
   networks:
    vp-network:
     aliases:
      - server2.docker      
  db:
   hostname: "db"
   image: mysql:5.6.28
   volumes:
     - /var/lib/mysql
   ports:
     - "3306:3306"
   expose:
     - 3306      
   networks:
    vp-network:
     aliases:
      - server3.docker      
   environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
     - MYSQL_DATABASE=${MYSQL_DATABASE:-dbname}
     - MYSQL_USER=${MYSQL_USER:-dbuser}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD:-dbpassword}
 networks:
         vp-network:
                 driver: bridge

